name: todo_app
description: A new todo project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  equatable: ^2.0.5
  go_router: ^6.2.0
  flutter_adaptive_scaffold: ^0.1.0
  uuid: ^3.0.7
  flutter_bloc: ^8.1.2
  either_dart: ^0.3.0
  json_annotation: ^4.8.0
  hive_flutter: ^1.1.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true
