name: todo_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.2.1
  flutter_adaptive_scaffold: ^0.1.11+1
  uuid: ^4.4.2
  either_dart: ^1.0.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.6
  shimmer_animation: ^2.2.1
  json_annotation: ^4.9.0
  hive: ^2.2.3
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  firebase_ui_auth: ^1.15.0
  cloud_firestore: ^5.1.0
  meta: ^1.12.0
  firebase_crashlytics: ^4.0.3
  path_provider: ^2.1.3
  easy_localization: ^3.0.7
  alchemist: ^0.7.0

dev_dependencies:
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
  - assets/translations/