name: todo_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  go_router: ^13.2.3
  flutter_adaptive_scaffold: ^0.1.10+1
  uuid: ^4.4.0
  either_dart: ^1.0.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.5
  shimmer_animation: ^2.1.0+1
  json_annotation: ^4.8.1
  hive: ^2.2.3
  firebase_core: ^2.29.0
  firebase_auth: ^4.19.1
  firebase_ui_auth: ^1.13.1
  cloud_firestore: ^4.16.1
  meta: ^1.11.0
  firebase_crashlytics: ^3.5.1
  path_provider: ^2.1.3
  easy_localization: ^3.0.5
  alchemist: ^0.7.0

dev_dependencies:
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
  - assets/translations/